article/urls.py
from django.urls import path, include
from article import views

app_name = 'article'
urlpatterns = [
    path('add/',views.add, name='add'),
    path('<int:id>-<slug:slug>/',views.detail, name='detail'),
    path('<int:id>/edit/',views.edit, name='edit'),
    path('<int:id>/delete/',views.delete, name='delete'),

]

user/urls.py
from django.urls import path, include
from user import views

app_name='user'

urlpatterns = [
    path('register/', views.register, name ='register'),
    path('login/', views.loginView, name ='login'),
    path('logout/', views.logoutView, name ='logout'),
    path('', views.dashboard, name ='dashboard'),
    path('articles', views.articles, name ='articles'),

]

zakirsblog/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.index, name ='index'),
    path('search/', main_views.search, name ='search'),    
    path('about/', main_views.about, name ='about'),
    path('user/', include('user.urls'), name='user'),
    path('article/', include('article.urls'), name='article'),
    path('tags/<slug:name>/',main_views.tags, name='tags'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
User = settings.AUTH_USER_MODEL
import os
import random
from django.utils.text import slugify

def upload_to(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return '%s/user_%s/%s%s'%('article',instance.author.id,random.randrange(100,999),file_extension)

class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Taq')
    slug = models.SlugField(max_length=100, unique=True,blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs) # Call the real save() method

    class Meta:
        verbose_name = 'Taq'
        verbose_name_plural = 'Taqlar'
        ordering = ['name']

    def __str__(self):
        return self.name
    

class Article(models.Model):
    author = models.ForeignKey(User, verbose_name = 'Müəllif',related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Başlıq', blank=False, null=False)
    content = RichTextField(max_length=5000, verbose_name='Yazı', blank=False, null=False)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Tarix')
    image = models.ImageField(blank=True, null=True, verbose_name='Başlıq Şəkli', upload_to=upload_to)
    tags = models.ManyToManyField(Tag, verbose_name='Taqlar')
    slug = models.SlugField(max_length=250, editable=False)

    class Meta:
        verbose_name = 'Məqalə'
        verbose_name_plural = 'Məqalələr'
        ordering = ('-created_date',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return '%  %' % (self.title,self.author)
    
    def get_img_or_default(self):
        if self.image and hasattr(self.image,'url'):
            return self.image.url
        return '/media/img/default.jpg'



class Comment(models.Model):
    author = models.ForeignKey(User, related_name='comment', on_delete=models.CASCADE, verbose_name='Yazan')
    article = models.ForeignKey(Article, related_name='comments',on_delete=models.CASCADE, verbose_name='Məqalə')
    created_date = models.DateTimeField(auto_now_add=True,verbose_name='Tarix')
    content = models.TextField(max_length=500,verbose_name='Şərh')

    class Meta:
        verbose_name = 'Şərh'
        verbose_name_plural = "Şərhlər"
        ordering = ('-created_date',)


    def __str__(self):
        return '{} > {}'.format(self.author,self.article)
    
    def __unicode__(self):
        return '{} > {}'.format(self.author,self.article)

templates/about.html
{% extends "layout.html" %}

{% block body %}
 {% comment %} <div id="app">
     [[term]] <br>
        <input v-model="term">
    <p v-for="(article,index) in articles">
        [[article.label]] <br>
        [[article]] <br>                
        [[index]] <br>
        <br>
    </p> 
</div> {% endcomment %}
<div class="display-4 text-center">Zakir Abdullayev</div>
<hr>
<div class="text-center">
<p>
    1997-ci il İyul ayının 19-u Mingəçevir şəhərində dünyaya gəlmişəm. 2015-ci ildə 
    <abbr title="Azərbaycan Texniki Universiteti" class="initialism">AzTU</abbr>-nun İstilik Energetikası Mühəndisliyi ixtisasına qəbul olmuşam
    və burda təhsilimi davam etdirməkdəyəm.
</p>
<p>
    Uşaqlıqdan bəri Kompyuterlərə və dolayısıyla proqramlaşdırmaya marağım olub və 14 yaşımdan özüm öyrənməyə başlamışam.
    Bu öyrənmə müddətində çoxlu qısa və uzun fasilələr olub. Motivasiya azlığı, abituriyentlik və s. bunların səbəbidir.
    2018-ci ildən Python proqramlaşdırma dilini və bu dilə aid əlavə modulları öyrənirəm. 
</p>

</div>
{% endblock body %}



{% comment %} {% block endkod %}

<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    var url = "/search/?term=";
    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
          articles: [],
          term:'axtar',
        },
        
        mounted() {
            
            axios.get(url + this.term).then(response => {
              this.articles = response.data
            })
          }
      })
</script>

{% endblock endkod %} {% endcomment %}

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block kod %}
<link rel="stylesheet" href="{% static 'jquery-ui/jquery-ui.css' %}">
<style>

        .crop img {
       height: 180px;
       object-fit: cover;
       width: 100%;
       }
       </style>
       
{% endblock kod %}

{% block body %}
<div class="row">
      
    <div class="col-12">
                <form method="GET">
            <div class="input-group mb-3 input-group-lg">
                <input id="search" type="text" name="term" class="form-control"
                {% if request.GET.term %}
                value="{{request.GET.term}}"
                {% endif %} placeholder="Axtar..." autocomplete="off" aria-label="Axtar" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Axtar</button>
                </div>
            </div>
        </form>
            {% if request.user.is_authenticated %}
            <a href="{% url 'article:add' %}" class="d-block d-md-none btn btn-info mb-4">Məqalə yaz</a>
            {% endif %}
    </div> <!-- col-12 -->
    <div class="col-md-8"> <!-- posts side -->
        {% if TagName %}
            <h2> <span class="badge badge-info">{{TagName}}</span></h2>
        {% endif %}
        
        <div class="row">
{% for article in articles  %}
        <div class="col-12">
            <div class="card mb-4">
            <div class="crop">
                <img class="card-img-top" src="{{article.get_img_or_default}}" alt="Card image cap">
            </div>
            <div class="card-body">
                    {% for tag in article.tags.all|slice:":3" %}
                    <span class="badge badge-info">{{tag}}</span>
                    {% endfor %}
                    <h5 class="card-title">{{article.title}}</h5>
                <p class="card-text"> 
                    
                    {{article.content|striptags|truncatewords:40|safe}} 
                </p>
                <!-- <p class="card-text">
                    <small class="text-muted">
                        {{article.created_date|timesince}} əvvəl 
                        <a href="{% url 'user:dashboard' %}">{{article.author.username}}</a> yazıb
                    </small>
                </p> -->
            </div>
                <div class="card-footer clearfix">
                <small class="text-muted float-left">
                    {{article.created_date|timesince}} əvvəl 
                   <a href="{% url 'user:dashboard' %}">{{article.author.username}}</a> yazıb
                </small>
                    <a href="{% url 'article:detail' article.id article.slug %}" class="btn btn-info float-right">Ətraflı</a>
            </div>      
        </div> <!-- card -->
    </div> <!-- col-12 -->
    {% empty%}
    <div class="col-12">
        <div class="alert alert-warning d-block">Məqalə yoxdur</div>
    </div>
{% endfor %}
    </div> <!-- row -->

<!-- pagination -->
{% if articles.has_other_pages %}
<hr>
<nav aria-label="pagination">
        <ul class="pagination">
            {% if articles.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{articles.previous_page_number}}{% if request.GET.term %}&term={{request.GET.term}}{% endif %}" tabindex="-1">&laquo;</a>
          </li>
            {% endif %}
            {% for page in articles.paginator.page_range %}
            {% if articles.number == page %}
            <li class="page-item active">
                <span class="page-link">
            {{articles.number}}
        </span>
          </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{page}}{% if request.GET.term %}&term={{request.GET.term}}{% endif %}">{{page}}</a>
            </li>
            {% endif %}
            
            {% endfor %}
          
          {% if articles.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{articles.next_page_number}}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">&raquo;</a>
          </li>
          
          {% endif %}
        </ul>
      </nav>
{% endif %}
</div> <!-- post side -->
<div class="col-md-4"> <!-- sidebars -->
    {% if request.user.is_authenticated %}
    <a href="{% url 'article:add' %}" class="d-none d-md-block btn btn-info mb-4 btn-lg">Məqalə yaz</a>
    {% endif %}
    <div class="card mb-4">
        <div class="card-header">Taqlar</div>
        <div class="card-body">
            <div class="row">
                {% for tag in tags %}
                <div class="col-6 col-md-12 col-lg-6">
                    <a href="{% url 'tags' tag.slug %}" class="btn btn-info my-1 d-block">
                        {{tag.name}} <span class="badge badge-light">{{tag.article_set.all|length}}</span>
                    </a>
                </div>
                {% endfor %}
            </div>
            </div>
        </div>
    </div>
</div><!-- row -->
        

{% endblock body %}
{% block endkod %}
<script src="{% static 'jquery-ui/jquery-ui.js' %}"></script>
    
<script>
  $(document).ready(function(){
    
    $( "#search" ).autocomplete({
      source: '/search',
      select: function(event,ui){
        window.location.href = '/article/' + ui.item.id
      },
      minLength: 2
    });
  } );
  </script>

{% endblock endkod %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    {% block kod %}    {% endblock kod %}
    <title>{% block title %}Zakir's Blog{% endblock title %}</title>
</head>
<body>
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/">Zakir's Blog</a>
                {% if request.user.is_authenticated %}
                <span class="navbar-text mr-1 d-block d-lg-none">Salam, {{request.user.username}}</span>
                {% else %}
                {% endif %}

                <div class="collapse navbar-collapse" id="navbarText">
                  
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'about' %}">Haqqımda</a>
                    </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">    
              {% if request.user.is_authenticated %}
                      <li class="nav-item d-none d-lg-block">
                        <span class="navbar-text mr-1">Salam, {{request.user.username}} |</span>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:dashboard' %}">Panel</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'user:logout' %}">Çıxış</a>
                        </li>
               {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Giriş</a>
                  </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Qeydiyyat</a>
              </li>
            {% endif %}
                   </ul>
                      
                </div>
                </nav>
              <div class="container mt-4 mb-4">
                  {% if messages %}
                      {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                      {% endfor %}
                  {% endif %}
    {% block body %}
    
    {% endblock body %}
            </div>
            <nav class="navbar sticky navbar-light bg-light">
              
            <span class="navbar-text mr-1"> Coded with <i class="fas fa-poop" style="color:brown;"></i> by </span>
                  
                  <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="https://fb.me/Z.Abdullayev.97"> Zakir Abdullayev</a>
                  </li>
              </ul>
                </nav>

    <script src="{% static 'jquery.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
                {% block endkod %}
                
                {% endblock endkod %}

  </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="offset-lg-3 col-lg-6 ">
        <div class="display-4">Giriş</div>
    <hr>
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Daxil ol</button>
    </form>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="offset-lg-3 col-lg-6 ">
<div class="display-4"> Qeydiyyat</div>
<hr>
<form action="" method="post">
    {% csrf_token %}
{{form|crispy}}
<button class="btn btn-success" type="submit">Qeydiyyat</button>
</form>
</div>

{% endblock body %}