article/urls.py
from django.urls import path, include
from article import views

app_name = 'article'
urlpatterns = [
    path('add/',views.add, name='add'),
    path('<int:id>-<slug:slug>/',views.detail, name='detail'),
    path('<int:id>/edit/',views.edit, name='edit'),
    path('<int:id>/delete/',views.delete, name='delete'),

]

user/urls.py
from django.urls import path, include
from user import views

app_name='user'

urlpatterns = [
    path('register/', views.register, name ='register'),
    path('login/', views.loginView, name ='login'),
    path('logout/', views.logoutView, name ='logout'),
    path('', views.dashboard, name ='dashboard'),
    path('articles', views.articles, name ='articles'),

]

zakirsblog/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.index, name ='index'),
    path('search/', main_views.search, name ='search'),    
    path('about/', main_views.about, name ='about'),
    path('user/', include('user.urls'), name='user'),
    path('article/', include('article.urls'), name='article'),
    path('tags/<slug:name>/',main_views.tags, name='tags'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
User = settings.AUTH_USER_MODEL
import os
import random
from django.utils.text import slugify

def upload_to(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return '%s/user_%s/%s%s'%('article',instance.author.id,random.randrange(100,999),file_extension)

class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Taq')
    slug = models.SlugField(max_length=100, unique=True,blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs) # Call the real save() method

    class Meta:
        verbose_name = 'Taq'
        verbose_name_plural = 'Taqlar'
        ordering = ['name']

    def __str__(self):
        return self.name
    

class Article(models.Model):
    author = models.ForeignKey(User, verbose_name = 'Müəllif',related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Başlıq', blank=False, null=False)
    content = RichTextField(max_length=5000, verbose_name='Yazı', blank=False, null=False)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Tarix')
    image = models.ImageField(blank=True, null=True, verbose_name='Başlıq Şəkli', upload_to=upload_to)
    tags = models.ManyToManyField(Tag, verbose_name='Taqlar')
    slug = models.SlugField(max_length=250, editable=False)

    class Meta:
        verbose_name = 'Məqalə'
        verbose_name_plural = 'Məqalələr'
        ordering = ('-created_date',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return '%  %' % (self.title,self.author)
    
    def get_img_or_default(self):
        if self.image and hasattr(self.image,'url'):
            return self.image.url
        return '/media/img/default.jpg'



class Comment(models.Model):
    author = models.ForeignKey(User, related_name='comment', on_delete=models.CASCADE, verbose_name='Yazan')
    article = models.ForeignKey(Article, related_name='comments',on_delete=models.CASCADE, verbose_name='Məqalə')
    created_date = models.DateTimeField(auto_now_add=True,verbose_name='Tarix')
    content = models.TextField(max_length=500,verbose_name='Şərh')

    class Meta:
        verbose_name = 'Şərh'
        verbose_name_plural = "Şərhlər"
        ordering = ('-created_date',)


    def __str__(self):
        return '{} > {}'.format(self.author,self.article)
    
    def __unicode__(self):
        return '{} > {}'.format(self.author,self.article)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class MyUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True, null=True)

article/forms.py
from django import forms
from .models import Article, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, ButtonHolder, Submit

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','image','tags']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(CommentForm,self).__init__(*args, **kwargs)
        self.fields['content'].label = ""
        self.helper =FormHelper()
        self.helper.layout = Layout(
            Field('content', style='resize:none;', rows='5',id='content'),)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models import MyUser

class RegisterForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ['username','email','password1','password2','first_name']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, label='İstifadəçi adı')
    password = forms.CharField(max_length=128, label='Parol', widget=forms.PasswordInput())

article/views.py
from django.shortcuts import render,redirect, get_object_or_404, reverse
from .forms import ArticleForm, CommentForm
from django.contrib import messages
from .models import Article, Comment, Tag
from django.utils.text import slugify
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def add(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.slug = slugify(form.data['title'])
        article.save()
        article.tags.add(form.data['tags'])
        
        messages.success(request,'Məqalə əlavə olundu')
        return redirect('user:dashboard')
    return render(request,'article/add.html',{'form':form})

@login_required
def edit(request, id):
    article = get_object_or_404(Article, id=id)
    if request.user.has_perm('article.change_article') or article.author==request.user:
        form = ArticleForm(instance=article,data=request.POST or None, files=request.FILES or None)
        if form.is_valid():
            form.save()
            messages.success(request,'Məqalə redəktə olundu')
            return redirect('article:detail',id=article.id, slug=article.slug)
        return render(request, 'article/edit.html',{'form':form})
    else:
        messages.warning(request,'Buna icazəniz yoxdur')
        return redirect('index')

@login_required
def delete(request, id):
    article = get_object_or_404(Article, id=id)
    if request.user.has_perm('article.delete_article') or article.author==request.user:
        article.delete()
        messages.success(request,'Məqalə silindi')
        return redirect('index')
    else:
        messages.warning(request,'Buna icazəniz yoxdur')
        return redirect('index')


def detail(request,id,slug='default'):
    article = get_object_or_404(Article,id=id)
    form = CommentForm(request.POST or None)
    if form.is_valid() and request.user.is_authenticated:
        comment = form.save(commit=False)
        comment.article = article
        comment.author = request.user
        comment.save()
        form = CommentForm()
    return render(request,'article/detail.html',{'article':article,'form':form})

# TAG
def tags(request,name):
    articles = Article.objects.filter(tags__name=name)
    paginator = Paginator(articles, 4)
    page = request.GET.get('page', 1)
    tags = Tag.objects.all()
    try:
        articles = paginator.get_page(page)
    except PageNotAnInteger:
        articles = paginator.get_page(1)
    except EmptyPage:
        articles = paginator.get_page(paginator.num_pages)
    return render(request,'index.html',{'articles':articles,'tags':tags})

user/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from .forms import RegisterForm, LoginForm
from django.contrib import messages 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from article.models import Article
User = settings.AUTH_USER_MODEL

# Create your views here.
def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,'Uğurla Qeydiyyatdan keçdiniz')
        return redirect('index')
    return render(request, 'register.html', context = {'form':form})

def loginView(request):
    if request.user.is_authenticated:
        return redirect('index')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request,'Uğurla daxil oldunuz')
            return redirect('index')
        else:
            messages.warning(request, 'İstifadəçi adı və ya şifrə səhvdir')
    return render(request, 'login.html',{'form':form})

def logoutView(request):
    logout(request)
    messages.success(request,'Uğurlu çıxış')
    return redirect('index')

@login_required
def dashboard(request):
    articles = Article.objects.filter(author=request.user)[:3]
    return render(request,'user/dashboard.html',{'articles':articles})

@login_required
def articles(request):
    articles = Article.objects.filter(author=request.user)
    paginator = Paginator(articles, 10)
    page = request.GET.get('page', 1)
    try:
        articles = paginator.get_page(page)
    except PageNotAnInteger:
        articles = paginator.get_page(1)
    except EmptyPage:
        articles = paginator.get_page(paginator.num_pages)
    return render(request,'user/articles.html',{'articles':articles})

templates/user/articles.html
{% extends "layout.html" %}
{% block title %}
Məqalələrim
{% endblock title %}
{% block body %}
{% if articles %}
<div class="display-4">Məqalələrim ({{articles.paginator.count}})</div>
<hr>
<div class="table-responsive">
        <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Başlıq</th>
                    <th scope="col">Tarix</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                {% for article in articles %}
                  <tr>
                    <th scope="row">{{article.id}}</th>
                    <td><a href="{% url 'article:detail' article.id article.slug %}">{{article.title}}</a></td>
                    <td>{{article.created_date}}</td>
                    <td><a href="{% url 'article:edit' article.id %}" class="btn btn-info">Dəyiş</a>
                    <a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
                  </tr>
                
                {% endfor %}
                  
                </tbody>
              </table>
            </div>
            {% if articles.has_other_pages %}
            <hr class="mt-3">
            <nav aria-label="pagination">
                    <ul class="pagination">
                        {% if articles.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{articles.previous_page_number}}" tabindex="-1">&laquo;</a>
                      </li>
                        {% endif %}
                        {% for page in articles.paginator.page_range %}
                        {% if articles.number == page %}
                        <li class="page-item active">
                            <span class="page-link">
                        {{articles.number}}
                    </span>
                      </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page}}">{{page}}</a>
                        </li>
                        {% endif %}
                        
                        {% endfor %}
                      
                      {% if articles.has_next %}
                      <li class="page-item">
                        <a class="page-link" href="?page={{articles.next_page_number}}">&raquo;</a>
                      </li>
                      
                      {% endif %}
                    </ul>
                  </nav>
            {% else %}
            {% endif %}
                        {% else %}
            <div class="alert alert-warning">
                Məqaləniz yoxdur
            </div>
            {% endif %}
        
{% endblock body %}

templates/user/dashboard.html
{% extends "layout.html" %}

{% block body %}
<div class="display-4">Panel <small class="text-muted">{{request.user.username}}</small></div>
<hr>
<a href="{% url 'article:add' %}" class="btn btn-success">Məqalə yaz</a>
<a href="{% url 'user:articles' %}" class="btn btn-info">Məqalələrim</a>
<hr>
{% if articles %}
<p class="lead">Son yazdıqlarım</p>
<div class="table-responsive">
<table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Başlıq</th>
            <th scope="col">Tarix</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id article.slug %}">{{article.title}}</a></td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:edit' article.id  %}" class="btn btn-info">Dəyiş</a>
            <a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
          </tr>
        
        {% endfor %}
          
        </tbody>
      </table>
    </div>
    {% else %}
    <div class="alert alert-warning">
        Məqaləniz yoxdur
    </div>
    {% endif %}

{% endblock body %}